### ISSUE TITLE
Add initial support for pre-computed aggregates

### ISSUE THREAD

**Issue by jsanda** [rhq-project/rhq-metrics#121]
The motivations for pre-computed aggregates are discussed in this [forum thread](https://developer.jboss.org/thread/249480). For the initial implementation we want to support,

* Tenant level configuration for rollup intervals, e.g., 5 min, 15 min, 1 hr, 1 day, etc.
  * Default to 1 hr, 6 hr, and 24 hr if the client does not specify anything for the tenant
* Compute max/min/avg
* Use fixed time windows as we did in RHQ
  * Investigate using sliding windows, like moving averages

This is intentionally a minimal feature set in order to 1) solicit feedback sooner and 2) use that feedback to help determine what additional features we want.

Note that the data and tags tables have a ```interval``` column. The purpose of this column was to more explicitly identify rollups. Every metric has an id, and every id consists of a name and an interval. For raw metrics, the interval is the empty string. Since there is no support yet for pre-computed aggregates, the interval is excluded from requests/responses in the REST API. We might want to rename the ```interval``` column to ```rollup``` to be more descriptive in its purpose.

There is some other stuff in the schema, specifically in ```schema.cql``` for dealing with pre-computed aggregates, but nothing has been done with it so we can change it freely as we see fit.

Let's say for example that we create a tenant with the following rollups,

* 15 minutes
* 30 minutes
* 1 hr
* 1 day

The 15 minute aggregate metric data would be computed from the raw metric data. The 30 minute data would be computed from the 15 minute data. The 1 hour data would be computed from the 30 minute data. And finally the 1 day data would be computed from the 30 minute data.

We can address querying pre-computed aggregate data in a separate ticket.

Lastly, for this ticket assume that there is only a single RHQ Metrics instance. There is ongoing investigation into multi-node deployments and coordinating work between nodes. We will start addressing that in subsequent tickets/iterations.

**Comment by jsanda** [comment]
There will be a good bit of work involved just for the initial support, so I think it might be helpful to break it up into subtasks. I will create separate tasks that have the _aggregation task_ label. If there is a dependency between tasks, it will be noted in the description.

**Comment by tsegismont** [comment]
> There will be a good bit of work involved just for the initial support,
> so I think it might be helpful to break it up into subtasks. I will
> create separate tasks that have the /aggregation task/ label. If there
> is a dependency between tasks, it will be noted in the description.

We'll soon move to JIRA so don't worry too much about the labels... In 
JIRA we can create subtasks IIRC

**Comment by jsanda** [comment]
This issue has been ported to JIRA - https://issues.jboss.org/browse/HWKMETRICS-1

**Comment by pilhuhn** [comment]
Can we please first discuss use cases for the pre-computed aggregates? We should not implement them just because RHQ has them. 
I am not saying that they are not useful, but we should try to better understand what we get from them, when they are used (e.g. you have 1h, 6h, 1d avg and 7 days raw retention. What data from what aggregate (raw, 1d, 6h,..) is used for e.g. a display range of 15days ago to 6days ago; this clearly spans the whole range.
Also do we know that min/max/avg is really what we want? What about 99%ile or such?
